#!/usr/bin/lua

local home = os.getenv("HOME")
local config = dofile(home .. "/.config/nvcs/config.lua")

local labelParam = table.concat(config, "\n")

function capture(cmd)
	local f = assert(io.popen(cmd, "r"))
	local s = assert(f:read("*a"))
	f:close()
	s = string.gsub(s, "^%s+", "")
	s = string.gsub(s, "%s+$", "")
	s = string.gsub(s, "[\n\r]+", " ")
	return s
end

local selection = capture('echo "' .. labelParam .. '"' .. "| rofi -dmenu -p 'Neovim config'")

if selection ~= nil and selection ~= "" then
	local file = io.open(home .. "/.config/nvcs/env.lua", "w")
	file:write(home .. "/.config/nvcs/envs/" .. selection .. "\n")
	file:close()
end
